---
title: "Stats Basics"
output: html_document
date: "2023-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


---
output:
  pdf_document: default
  html_document: default
---

```{r}
Personality = read.csv("Basics Data.csv")

View(Personality)

mean(Personality$helpful)

```

```{r}
#Choosen Characterstic is helpful

Personality$helpful
```



```{r}
#Independent t#
t.test(Personality$helpful, mu=4.5)
#Its P value is very very low so we can conclude that this is not from the same sample.
```



```{r}
library(MOTE)
m = mean(Personality$helpful, na.rm=0)

sd = sd(Personality$helpful)

n = length(Personality$helpful)

c(m,sd,n)

d.single.t(m=m, sd=sd, n=n, u=4.5, a = 0.05)
```



```{r}
#Dependent T
# Lets create temperory data set
library(reshape)
 temp = data.frame(Personality$lovchil, Personality$foullang)

colnames(temp) = c('lovchil','foullang')

temp$partno = 1:length(temp$lovchil)

templong = melt(temp, id= "partno", measured= c("lovchil","foullang"))

colnames(templong) = c('partno', 'time', 'score')

t.test(templong$score ~ templong$time, paired=T ##because dependent t##
       , var.equal = T)

#Since its p-value is very small we can conclude both of these belong to different populations and are not same

M = tapply(templong$score, templong$time, mean, rm.na=T)

stdev = tapply(templong$score, templong$time, sd)

N = tapply(templong$score, templong$time, length)

M;stdev;N

d.dep.t.avg(m1 = 6.15, m2 = 4.23, sd1 = 1.22, sd2= 2.11, n=369)
```


```{r}
#Applying ndependent t on time and helpful rating

Personality$semestertime = factor(Personality$semestertime, levels = c(1,2), labels = c("Early", "Late"))
Personality$semestertime
t.test(Personality$helpful ~ Personality$semestertime, paired=F ##because dependent t##
       , var.equal = T)
M= tapply(Personality$helpful, list(Personality$semestertime), mean)

stdev = tapply(Personality$helpful, list(Personality$semestertime), sd)

N = tapply(Personality$helpful, list(Personality$semestertime), length)

M;stdev;N

d.ind.t(m1= 6.07, m2 = 6.02, sd1 = 1.02, sd2= 0.97, n1=189, n2=189, a =0.05)
#P value is quite high and 0 is part of confidence interval hence we can say that this does not matter
```

```{r}
#Correlation
library(Hmisc)

rcorr(Personality$feminine, Personality$masculin)

Corr_Data = data.frame(Personality$feminine, Personality$masculin)

rcorr(as.matrix(Corr_Data))


```


